version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: sf6_mysql
    volumes:
      - .docker/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    networks:
      - symfony

  php:
    build: 
      context: .docker/php
    container_name: sf6_php
    ports:
      - 9000:8000
    volumes:
      - ./app:/var/www/html
    depends_on:
      - mysql
    networks:
      - symfony

volumes:
  data:

networks:
  symfony: